# -*- coding: utf-8 -*-
"""4_Despliegue_Validación_Cruzada_AtaqueCorazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LF0ZQlF9lHnpn6SwfVDN8_Do-EgUE2cs

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo,labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

def make_prediction(input_df, modelo, min_max_scaler, variables, labelencoder):
    data_preparada = input_df.copy()

    # Convert binary categorical columns ('Yes'/'No') to 0/1
    for col_name in ['hypertension', 'heart_disease', 'ever_married']:
        if col_name in data_preparada.columns:
            data_preparada[f'{col_name}_Yes'] = data_preparada[col_name].apply(lambda x: 1 if x == 'Yes' else 0).astype(int)
            data_preparada = data_preparada.drop(columns=[col_name])

    # Apply get_dummies for 'smoking_status'
    if 'smoking_status' in data_preparada.columns:
        data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status'], drop_first=False, dtype=int)

    # Reindex to ensure all expected 'variables' are present and in order
    data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

    # Normalize numerical features
    numerical_features = ['age', 'avg_glucose_level']
    if not data_preparada.empty and all(feature in data_preparada.columns for feature in numerical_features):
        data_preparada[numerical_features] = min_max_scaler.transform(data_preparada[numerical_features])
    else:
        return "Error en la preparación de datos (faltan características numéricas)"

    # Make prediction
    if not data_preparada.empty:
        Y_pred = modelo.predict(data_preparada)
        # Use labelencoder to inverse_transform the numerical prediction back to original labels
        return labelencoder.inverse_transform(Y_pred)
    else:
        return "No hay datos para realizar la predicción"

# Define expected input columns for a placeholder DataFrame
initial_columns = ['age', 'avg_glucose_level', 'hypertension', 'heart_disease', 'ever_married', 'smoking_status']

# Initialize 'data' with an empty DataFrame with expected columns.
# This ensures 'data' is always defined, preventing NameErrors in downstream cells,
# especially when running outside a live Streamlit environment or if inputs are not set.
data = pd.DataFrame(columns=initial_columns)

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title('Predicción de Posibles Ataques al Corazon')

# File uploader section
uploaded_file = st.file_uploader("Upload your CSV file for prediction", type=['csv'])

data = pd.DataFrame(columns=initial_columns) # Ensure data is defined

# Conditional assignment of 'data' based on user input
if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.subheader("Uploaded data preview:")
    st.dataframe(data.head())
else:
    st.subheader("Or enter data manually:")
    Edad = st.slider('age', min_value=1, max_value=82, value=44, step=1)
    Nivel_glucosa_promedio = st.slider('avg_glucose_level', min_value=55, max_value=272, value=106, step=1)
    Hipertension = st.selectbox('hypertension', ['No', 'Yes'])
    Enfermedad_Cardiaca = st.selectbox('heart_disease', ['No', 'Yes'])
    Casado = st.selectbox('ever_married', ['No', 'Yes'])
    Estado_Fumador = st.selectbox('smoking_status', ["'never smoked'", 'Unknown',"'formerly smoked'","smokes"])

    datos = [[Edad, Nivel_glucosa_promedio, Hipertension, Enfermedad_Cardiaca, Casado, Estado_Fumador]]
    # `initial_columns` is defined in cell `hPWW9cckatVW` and assumed to be available globally.
    data = pd.DataFrame(datos, columns=initial_columns)

# Now, always process and display the data with prediction
if not data.empty:
    st.subheader("Datos procesados y predicción:")
    # Make prediction
    prediction_result = make_prediction(data.copy(), modelo, min_max_scaler, variables, labelencoder)

    # Check if prediction_result is a string (error message) or an array of predictions
    if isinstance(prediction_result, str):
        st.error(f"Error al realizar la predicción: {prediction_result}")
    else:
        # Add the prediction result as a new column to the DataFrame
        data['Prediccion'] = prediction_result

        # Display the full data with prediction
        st.dataframe(data)

        # --- New Filtering Section ---
        st.markdown("---") # Separator for better UI
        st.subheader("Filtros Interactivos y Visualización:")

        # Use data.copy() to avoid SettingWithCopyWarning if original data is used later in different ways
        data_for_filters_plots = data.copy()

        # Check if data_for_filters_plots is empty before proceeding with filters and plots
        if data_for_filters_plots.empty:
            st.warning("No hay datos disponibles para aplicar filtros o visualizaciones.")
        else:
            # Initialize ranges with default values that are broad enough for any data,
            # and that can be overridden by actual data mins/maxs.
            # These are also used as fallback if a column is missing or non-numeric.
            age_range = (1, 100) # Broad default range for age
            glucose_range = (0.0, 300.0) # Broad default range for glucose

            # --- Numerical Filters ---
            st.markdown("##### Filtros Numéricos:")
            num_col1, num_col2 = st.columns(2)

            # Age filter
            if 'age' in data_for_filters_plots.columns and pd.api.types.is_numeric_dtype(data_for_filters_plots['age']):
                age_series = data_for_filters_plots['age'].dropna()
                if not age_series.empty:
                    min_age_val = int(age_series.min())
                    max_age_val = int(age_series.max())
                    if min_age_val < max_age_val: # Only create slider if there's a range
                        with num_col1:
                            age_range = st.slider('Rango de Edad', min_age_val, max_age_val, (min_age_val, max_age_val))
                    else: # min_age_val == max_age_val (single unique value)
                        with num_col1:
                            st.write(f"Edad: {min_age_val}")
                            age_range = (min_age_val, max_age_val) # Set range to single value for filtering
                else:
                    with num_col1:
                        st.write("Columna 'age' vacía o con solo valores nulos para el filtro.")
            else:
                with num_col1:
                    st.write("Columna 'age' no encontrada o no numérica.")

            # Avg Glucose Level filter
            if 'avg_glucose_level' in data_for_filters_plots.columns and pd.api.types.is_numeric_dtype(data_for_filters_plots['avg_glucose_level']):
                glucose_series = data_for_filters_plots['avg_glucose_level'].dropna()
                if not glucose_series.empty:
                    min_glucose_val = float(glucose_series.min())
                    max_glucose_val = float(glucose_series.max())
                    if min_glucose_val < max_glucose_val: # Only create slider if there's a range
                        with num_col2:
                            glucose_range = st.slider('Nivel Promedio de Glucosa', min_glucose_val, max_glucose_val, (min_glucose_val, max_glucose_val))
                    else: # min_glucose_val == max_glucose_val
                        with num_col2:
                            st.write(f"Nivel Promedio de Glucosa: {min_glucose_val}")
                            glucose_range = (min_glucose_val, max_glucose_val) # Set range to single value for filtering
                else:
                    with num_col2:
                        st.write("Columna 'avg_glucose_level' vacía o con solo valores nulos para el filtro.")
            else:
                with num_col2:
                    st.write("Columna 'avg_glucose_level' no encontrada o no numérica.")

            st.markdown("##### Filtros Categóricos:")
            # Create multiselect filters for categorical columns
            col1, col2 = st.columns(2)
            selected_hypertension = []
            selected_heart_disease = []
            selected_ever_married = []
            selected_smoking_status = []

            # Hypertension filter
            if 'hypertension' in data_for_filters_plots.columns:
                unique_hypertension = data_for_filters_plots['hypertension'].dropna().unique().tolist()
                if unique_hypertension: # Check if list is not empty
                    with col1:
                        selected_hypertension = st.multiselect('Filtrar por Hipertensión', options=unique_hypertension, default=unique_hypertension)
                else:
                    with col1:
                        st.write("No hay datos válidos de 'Hipertensión' para filtrar.")

            # Heart Disease filter
            if 'heart_disease' in data_for_filters_plots.columns:
                unique_heart_disease = data_for_filters_plots['heart_disease'].dropna().unique().tolist()
                if unique_heart_disease:
                    with col1:
                        selected_heart_disease = st.multiselect('Filtrar por Enfermedad Cardiaca', options=unique_heart_disease, default=unique_heart_disease)
                else:
                    with col1:
                        st.write("No hay datos válidos de 'Enfermedad Cardiaca' para filtrar.")

            # Ever Married filter
            if 'ever_married' in data_for_filters_plots.columns:
                unique_ever_married = data_for_filters_plots['ever_married'].dropna().unique().tolist()
                if unique_ever_married:
                    with col2:
                        selected_ever_married = st.multiselect('Filtrar por Casado', options=unique_ever_married, default=unique_ever_married)
                else:
                    with col2:
                        st.write("No hay datos válidos de 'Casado' para filtrar.")

            # Smoking Status filter
            if 'smoking_status' in data_for_filters_plots.columns:
                unique_smoking_status = data_for_filters_plots['smoking_status'].dropna().unique().tolist()
                if unique_smoking_status:
                    with col2:
                        selected_smoking_status = st.multiselect('Filtrar por Estado Fumador', options=unique_smoking_status, default=unique_smoking_status)
                else:
                    with col2:
                        st.write("No hay datos válidos de 'Estado Fumador' para filtrar.")


            # Apply filters
            filtered_data = data_for_filters_plots.copy()

            # Apply numerical filters (only if corresponding columns exist)
            if 'age' in filtered_data.columns:
                filtered_data = filtered_data[
                    (filtered_data['age'] >= age_range[0]) & (filtered_data['age'] <= age_range[1])
                ]
            if 'avg_glucose_level' in filtered_data.columns:
                 filtered_data = filtered_data[
                    (filtered_data['avg_glucose_level'] >= glucose_range[0]) & (filtered_data['avg_glucose_level'] <= glucose_range[1])
                ]

            # Apply categorical filters
            if selected_hypertension:
                filtered_data = filtered_data[filtered_data['hypertension'].isin(selected_hypertension)]
            if selected_heart_disease:
                filtered_data = filtered_data[filtered_data['heart_disease'].isin(selected_heart_disease)]
            if selected_ever_married:
                filtered_data = filtered_data[filtered_data['ever_married'].isin(selected_ever_married)]
            if selected_smoking_status:
                filtered_data = filtered_data[filtered_data['smoking_status'].isin(selected_smoking_status)]

            st.subheader("Resultados Filtrados:")
            if not filtered_data.empty:
                st.dataframe(filtered_data)

                # --- Download Button ---
                csv = filtered_data.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="Descargar datos filtrados como CSV",
                    data=csv,
                    file_name='datos_prediccion_filtrados.csv',
                    mime='text/csv',
                )

                # --- Visualization Section ---
                if len(filtered_data) > 1: # Only show summary if more than one row after filtering
                    st.subheader("Resumen de Predicciones Filtradas:")
                    prediction_counts = filtered_data['Prediccion'].value_counts().reset_index()
                    prediction_counts.columns = ['Prediccion', 'Count']
                    st.bar_chart(prediction_counts, x='Prediccion', y='Count')
                else: # len(filtered_data) == 1
                    st.write("Solo hay una entrada filtrada para la predicción, no se muestra un resumen gráfico.")
            else:
                st.write("No hay entradas que coincidan con los filtros seleccionados.")

else:
    st.warning("No hay datos válidos para realizar la predicción.")