# -*- coding: utf-8 -*-
"""4_Despliegue_Validación_Cruzada_AtaqueCorazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LF0ZQlF9lHnpn6SwfVDN8_Do-EgUE2cs

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo,labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

# Define expected input columns for a placeholder DataFrame
initial_columns = ['age', 'avg_glucose_level', 'hypertension', 'heart_disease', 'ever_married', 'smoking_status']

# Initialize 'data' with an empty DataFrame with expected columns.
# This ensures 'data' is always defined, preventing NameErrors in downstream cells,
# especially when running outside a live Streamlit environment or if inputs are not set.
data = pd.DataFrame(columns=initial_columns)

import streamlit as st
import pandas as pd

st.title('Predicción de Posibles Ataques al Corazon')

# File uploader section
uploaded_file = st.file_uploader("Upload your CSV file for prediction", type=['csv'])

# Conditional assignment of 'data' based on user input
if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.subheader("Uploaded data preview:")
    st.dataframe(data.head())
else:
    st.subheader("Or enter data manually:")
    Edad = st.slider('age', min_value=1, max_value=82, value=44, step=1)
    Nivel_glucosa_promedio = st.slider('avg_glucose_level', min_value=55, max_value=272, value=106, step=1)
    Hipertension = st.selectbox('hypertension', ['No', 'Yes'])
    Enfermedad_Cardiaca = st.selectbox('heart_disease', ['No', 'Yes'])
    Casado = st.selectbox('ever_married', ['No', 'Yes'])
    Estado_Fumador = st.selectbox('smoking_status', ["'never smoked'", 'Unknown',"'formerly smoked'","smokes"])

    # Dataframe from sliders
    datos = [[Edad, Nivel_glucosa_promedio, Hipertension, Enfermedad_Cardiaca, Casado, Estado_Fumador]]
    data = pd.DataFrame(datos, columns=initial_columns)

st.write("Data to be processed:")
st.dataframe(data.head()) # Display the final 'data' DataFrame for confirmation

#Se realiza la preparación de datos
data_preparada = data.copy()

# Convert binary categorical columns ('Yes'/'No') to 0/1 and rename to match model's expected features
for col_name in ['hypertension', 'heart_disease', 'ever_married']:
    if col_name in data_preparada.columns:
        data_preparada[f'{col_name}_Yes'] = data_preparada[col_name].apply(lambda x: 1 if x == 'Yes' else 0).astype(int)
        data_preparada = data_preparada.drop(columns=[col_name])

# Apply get_dummies for 'smoking_status' as it's multi-categorical
# Based on the 'variables' array, all dummy columns are expected, so drop_first=False.
if 'smoking_status' in data_preparada.columns:
    data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status'], drop_first=False, dtype=int)

data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad y el nivel de glucosa para predecir
#En los despliegues no se llama fit

numerical_features = ['age', 'avg_glucose_level']

# Ensure data_preparada is not empty and has the numerical columns before scaling
if not data_preparada.empty and all(feature in data_preparada.columns for feature in numerical_features):
    data_preparada[numerical_features] = min_max_scaler.transform(data_preparada[numerical_features])
else:
    # This print will be visible in Colab output if the DataFrame is empty
    print("Warning: data_preparada is empty or missing numerical features for scaling. Skipping normalization.")

data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un exito del 81.3% (F1 Macro)")